project_id = "lfrkfthmlxrotqfrdmwq"

[functions.admin-users]
verify_jwt = false

[functions.demo-signup]
verify_jwt = false

[functions.onboarding-complete]
verify_jwt = false

[functions.join-tenant]
verify_jwt = false

[functions.get-tenant-structure]
verify_jwt = false

[functions.parse-efd-icms]
verify_jwt = false

[functions.process-efd-icms-job]
verify_jwt = false

[functions.parse-efd-emergency]
verify_jwt = false
[functions.parse-efd-v11]
enabled = true
verify_jwt = true
import_map = "./functions/parse-efd-v11/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/parse-efd-v11/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/parse-efd-v11/*.html" ]

[functions.parse-efd-v12]
enabled = true
verify_jwt = true
import_map = "./functions/parse-efd-v12/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/parse-efd-v12/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/parse-efd-v12/*.html" ]

[functions.parse-efd-v13]
enabled = true
verify_jwt = false
import_map = "./functions/parse-efd-v13/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/parse-efd-v13/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/parse-efd-v13/*.html" ]

[functions.process-efd-job]
verify_jwt = false

[functions.refresh-views]
verify_jwt = false
